### ISSUE TITLE
`Nullable.fromOption` does not return `null` for `None`

### ISSUE THREAD

**Issue by jquesada2016** [rescript-association/rescript-core#170] opened 2023-12-14 18:50 UTC
```rescript
None->Nullable.fromOption
```

should return `null`, but instead returns `undefined`, which is not the same. :(

**Comment by zth** [comment] 2024-01-04 11:02
This is actually intended. Maybe it's the naming that's a bit confusing, but `Null.t` and `Null.fromOption` would return `null` for `None`. `Nullable` has both `undefined` and `null`.

Closing since it's working as intended, but please feel free to continue the discussion.

**Closed by zth** 2024-01-04 11:02 UTC

**Comment by DZakh** [comment] 2024-01-04 11:21
Related to https://github.com/rescript-lang/rescript-compiler/issues/6533

**Comment by jquesada2016** [comment] 2024-01-04 17:06
Yes, this was exactly what got me. The `nullable` name made me assume it returned `null`, rather than it being a nomenclature fore both `null` and `undefined` coercing to `undefined`. I also thought `null` only defined the `null` constant value. I hadn't noticed `Null.t<'a>`.
